#!/usr/bin/env bun
// Installs a launcher at ~/.local/bin/nerve that runs *this repo's* index.ts via Bun.
//
// nerve is deliberately NOT a `bun build --compile` binary: it reads prompts/, config/, docs/
// and skills/ fresh from disk (resolved via import.meta.dir) and hot-swaps src/tools/ +
// interceptors via cache-busted dynamic import (CLAUDE.md "Hot-swap seams", DECISIONS D11).
// A compiled binary freezes all of that into /$bunfs and breaks /reload and the system-prompt
// hot-swap. A thin launcher keeps the self-hackable design intact and still puts nerve on PATH.
import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

const repo = resolve(import.meta.dir, "..");
const binDir = join(homedir(), ".local", "bin");
const target = join(binDir, "nerve");

const launcher = `#!/bin/sh
# Auto-generated by \`bun run build\` — runs nerve from its source repo so hot-reload works.
# Re-run \`bun run build\` from the repo if you move it.
exec bun "${repo}/index.ts" "$@"
`;

mkdirSync(binDir, { recursive: true });
writeFileSync(target, launcher);
chmodSync(target, 0o755);
console.log(`installed launcher → ${target}\n  runs: bun "${repo}/index.ts"`);
